sudo: required
dist: trusty

cache:
  directories:
    - release

install: true
script:
  - if [ ! -f release/lbrycrd-linux.zip ]; then  ./reproducible_build.sh -t; fi
  - if [ ! -f release/lbrycrd-linux.zip ]; then mkdir -p release; zip -j release/lbrycrd-linux.zip src/lbrycrdd src/lbrycrd-cli src/lbrycrd-tx; fi
